version: 0.2

phases:
  install:
    commands:
      - echo Installing Angular CLI...
      - npm install -g @angular/cli@17

  pre_build:
    commands:
      - echo Installing dependencies...
      - npm install

  build:
    commands:
      - echo Running Angular build for production...
      - ng build --configuration production

  post_build:
    commands:
      - echo Build phase completed successfully.

artifacts:
  files:
    - 'dist/my-angular-project/**/*'
    - appspec.yml
    - 'deploy-scripts/**/*'
