version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm install -g @angular/cli@17
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - ng build -c production
      - echo "Build Completed."
    finally:
      - echo This is the finally block execution!
artifacts:
  base-directory: dist/my-angular-project # Angular의 정확한 출력 경로
  files:
    - '**/*'                    # base-directory 안의 모든 파일을 의미
    - appspec.yml               # CodeDeploy용 파일
    - 'deploy-scripts/**/*'     # CodeDeploy용 스크립트 폴더